import { NextResponse } from 'next/server'

/**
 * POST /api/send-telegram-receipt
 *
 * Receives a base64-encoded PDF generated by jsPDF on the frontend,
 * converts it to a Buffer, and sends it to Telegram as a downloadable
 * document via the sendDocument endpoint.
 *
 * Body: { pdfBase64: string, order: object }
 *
 * This route is intentionally fire-and-forget from the client — it
 * never blocks or affects checkout completion.
 */
export async function POST(request) {
  try {
    const { pdfBase64, order } = await request.json()

    if (!pdfBase64 || !order?.id) {
      return NextResponse.json({ error: 'Missing pdfBase64 or order.id' }, { status: 400 })
    }

    const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN
    const CHAT_ID   = process.env.TELEGRAM_CHAT_ID

    if (!BOT_TOKEN || !CHAT_ID) {
      console.warn('[Receipt] TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID not set — skipping.')
      return NextResponse.json({ sent: false, reason: 'missing_config' })
    }

    // ── 1. Decode base64 → Buffer ─────────────────────────────────────────
    // jsPDF's datauristring format: "data:application/pdf;base64,<data>"
    const base64Data = pdfBase64.includes(',') ? pdfBase64.split(',')[1] : pdfBase64
    const pdfBuffer  = Buffer.from(base64Data, 'base64')
    const filename   = `receipt-${order.id}.pdf`

    // ── 2. Build caption ──────────────────────────────────────────────────
    const fmt      = n => 'UGX ' + Number(n || 0).toLocaleString('en-UG', { minimumFractionDigits: 0 })
    const fullName = [order.customer?.firstName, order.customer?.lastName].filter(Boolean).join(' ') || 'N/A'

    const payLabel = {
      cod:         'Cash on Delivery',
      mobilemoney: 'Mobile Money',
      card:        'Card Payment',
    }[order.paymentMethod] || order.paymentMethod || 'N/A'

    const caption = [
      `🧾 NEW ORDER RECEIPT`,
      ``,
      `📦 Order ID:  ${order.id}`,
      `👤 Customer:  ${fullName}`,
      `📱 Phone:     ${order.customer?.phone || 'N/A'}`,
      `💰 Total:     ${fmt(order.total)}`,
      `💳 Payment:   ${payLabel}`,
      ``,
      `Download the PDF above for the full receipt.`,
    ].join('\n')

    // ── 3. Send to Telegram via raw multipart Buffer ──────────────────────
    // We construct the multipart body manually instead of using FormData+Blob.
    // Node.js's native FormData silently drops the `filename` attribute when
    // appending a Blob, which causes Telegram to reject the upload. Building
    // the raw Buffer guarantees the correct Content-Disposition on every Node
    // runtime with zero extra dependencies.
    const boundary = `TgBoundary${Date.now()}`
    const CRLF     = '\r\n'

    const textPart = (name, value) =>
      `--${boundary}${CRLF}` +
      `Content-Disposition: form-data; name="${name}"${CRLF}` +
      CRLF +
      `${value}${CRLF}`

    const body = Buffer.concat([
      Buffer.from(textPart('chat_id', CHAT_ID)),
      Buffer.from(textPart('caption', caption)),
      Buffer.from(
        `--${boundary}${CRLF}` +
        `Content-Disposition: form-data; name="document"; filename="${filename}"${CRLF}` +
        `Content-Type: application/pdf${CRLF}` +
        CRLF
      ),
      pdfBuffer,
      Buffer.from(`${CRLF}--${boundary}--${CRLF}`),
    ])

    const res  = await fetch(
      `https://api.telegram.org/bot${BOT_TOKEN}/sendDocument`,
      {
        method:  'POST',
        headers: {
          'Content-Type':   `multipart/form-data; boundary=${boundary}`,
          'Content-Length': String(body.length),
        },
        body,
      }
    )

    const data = await res.json()

    if (!res.ok || !data.ok) {
      console.error('[Receipt] Telegram sendDocument error:', JSON.stringify(data))
      return NextResponse.json({ sent: false, reason: 'api_error', detail: data.description })
    }

    console.log(`[Receipt] ✅ PDF sent to Telegram for order ${order.id}`)
    return NextResponse.json({ sent: true })

  } catch (e) {
    // Never propagate — checkout must never be affected by receipt failures
    console.error('[Receipt] Unexpected error:', e.message)
    return NextResponse.json({ sent: false, reason: 'server_error', detail: e.message })
  }
}
